name: 'Deploy Dashboard Tracker'
description: 'Track deployments via the GitHub Deployments API for the deploy dashboard'
author: 'RKrogh'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  environment:
    description: 'Target environment name (e.g., dev, staging, prod)'
    required: true
  service:
    description: 'Service name for mono-repo support. Defaults to the repository name.'
    required: false
  version:
    description: 'Version string. Defaults to the short SHA of the current commit.'
    required: false
  status:
    description: 'Deployment status. One of: success, failure, error, inactive, in_progress, queued, pending.'
    required: false
    default: 'success'
  environment-url:
    description: 'URL to the deployed environment.'
    required: false
  description:
    description: 'Free-form description of the deployment.'
    required: false
  token:
    description: 'GitHub token for API authentication.'
    required: true
    default: '${{ github.token }}'
  dashboard-repo:
    description: 'Repository to write status files to (e.g., "org/deploy-dashboard"). Enables push-based static dashboard mode. If not set, no status file is written.'
    required: false
  dashboard-branch:
    description: 'Branch to write status files to in the dashboard repo.'
    required: false
    default: 'gh-pages'
  dashboard-token:
    description: 'Token with write access to the dashboard repo. Defaults to the main token input. Set this if the dashboard repo differs from the current repo.'
    required: false

outputs:
  deployment-id:
    description: 'The ID of the created GitHub deployment'
  service:
    description: 'The resolved service name'
  version:
    description: 'The resolved version string'

runs:
  using: 'node20'
  main: 'dist/index.js'
